query AllPosts {
    posts(skip: 1, orderBy: date_DESC) {
        date
        slug
        title
        excerpt
        type
        content {
            text
        }
        image {
            url
        }
    }
}
